apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: backend-pvc
    namespace: application
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/home/docker/backend-data"
  nodeAffinity: # <-- THIS SECTION IS CRITICAL
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: application
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi