---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cc-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.2-192.168.1.253 
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cc-advertisement
  namespace: metallb-system