apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    namespace: devops-tools
  name: argocd-cmd-params-cm
data:
  server.insecure: "true" 